version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
       - image: cimg/node:18.8.0
          # context / project UI env-var reference
    steps:
      - checkout
      - run: 
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}    
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules  
      - run: npm install      
      - run:
          name: test
          command: npm run test 
      - run:
          name: Upload coverage report to code cov
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB

  code-job:
      docker:
       - image: cimg/node:18.8.0
      steps:
       
        - codecov/upload:
            file: './codecov'
            
              
workflows:
  code-run:
    jobs:
      - build
       