version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
       - image: cimg/node:18.8.0
          # context / project UI env-var reference
    steps:
      - checkout
      - run: 
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}    
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules  
      - run: npm install      
      - run:
          name: test
          command: npm run test 
      - codecov/upload:
          token: e0556b3d-ddeb-4505-88af-0c41e6f50611 
          validate_url: true 
          upload_name: codecov/upload     
                   

 